# Generated by Django 3.2 on 2021-06-07 15:12

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields.related


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('lookupString', models.CharField(max_length=255)),
                ('pattern', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UrlMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_Name', models.CharField(max_length=255, unique=True)),
                ('url', models.ForeignKey(on_delete=django.db.models.fields.related.ForeignKey, to='accounts.urlname')),
            ],
        ),
        migrations.CreateModel(
            name='GroupUrlMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isAccess', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('urlMethod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.urlmethod')),
            ],
        ),
    ]
