# Generated by Django 3.2 on 2021-06-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmethod',
            name='method_Name',
            field=models.CharField(max_length=255),
        ),
    ]
