# Generated by Django 3.2 on 2021-05-06 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0004_auto_20210504_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='career.sector'),
        ),
    ]
