# Generated by Django 3.2 on 2021-05-10 13:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0005_alter_consultant_sector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modificationDate', models.DateTimeField(auto_now=True)),
                ('firstName', models.CharField(blank=True, max_length=64, null=True)),
                ('lastName', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='profile',
        ),
        migrations.AddField(
            model_name='instructor',
            name='title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='person',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='career.person'),
        ),
    ]
