# Generated by Django 3.2 on 2021-05-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0008_blog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
        migrations.AddField(
            model_name='blogdescription',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
