# Generated by Django 3.2 on 2021-05-17 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0009_auto_20210511_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='finishTime',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='startTime',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='lecturedescription',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='career.student'),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
