# Generated by Django 3.2 on 2021-05-17 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0011_auto_20210517_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='career.location'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='room',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='room',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
