# Generated by Django 3.2 on 2021-05-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0015_auto_20210518_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
