# Generated by Django 3.2 on 2021-05-19 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0016_company_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='career.city'),
        ),
        migrations.AlterField(
            model_name='company',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='career.district'),
        ),
    ]
