# Generated by Django 3.2 on 2021-05-20 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0017_auto_20210519_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='militaryStatus',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='staffCount',
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='salaryMax',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='salaryMin',
            field=models.IntegerField(null=True),
        ),
    ]
