# Generated by Django 3.2 on 2021-05-22 14:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0018_auto_20210521_0116'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modificationDate', models.DateTimeField(auto_now=True)),
                ('jobPost', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='career.jobpost')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='career.student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
