# Generated by Django 3.2 on 2021-05-26 14:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0020_auto_20210524_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaritalStatusDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modificationDate', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.language')),
                ('maritalStatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.maritalstatus')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
