# Generated by Django 3.2 on 2021-05-27 07:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0021_maritalstatusdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='militaryDelayedDate',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='MilitaryStatusDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modificationDate', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.language')),
                ('militaryStatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.militarystatus')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
