# Generated by Django 3.2 on 2021-05-29 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0023_reference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foreignlanguagelevel',
            old_name='name',
            new_name='keyword',
        ),
        migrations.CreateModel(
            name='ForeignLanguageLevelDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('foreignLanguageLevel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.foreignlanguagelevel')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.language')),
            ],
        ),
    ]
