# Generated by Django 3.2 on 2021-05-31 11:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0026_studentexam'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDriverLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modificationDate', models.DateTimeField(auto_now=True)),
                ('driverLicense', models.CharField(max_length=12, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
