# Generated by Django 3.2 on 2021-05-31 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0027_studentdriverlicense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenteducationinfo',
            name='graduationDate',
            field=models.DateField(null=True),
        ),
    ]
