# Generated by Django 3.2 on 2021-06-04 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0031_blogtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blogType',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='career.blogtype'),
        ),
    ]
