# Generated by Django 3.2 on 2021-06-04 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0034_auto_20210604_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='url',
            new_name='website',
        ),
    ]
