# Generated by Django 3.2 on 2021-06-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0035_rename_url_unit_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='cvLink',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
