# Generated by Django 3.2 on 2021-06-15 14:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0041_menu_relationfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modificationDate', models.DateTimeField(auto_now=True)),
                ('isSuccessApplication', models.BooleanField(default=True)),
                ('scholarShip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='career.scholarship')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='career.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LectureApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modificationDate', models.DateTimeField(auto_now=True)),
                ('isSuccessApplication', models.BooleanField(default=True)),
                ('lecture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='career.lecture')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='career.student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
