# Generated by Django 3.2 on 2021-06-25 08:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0044_consultantcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modificationDate', models.DateTimeField(auto_now=True)),
                ('link', models.CharField(blank=True, max_length=256, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.company')),
                ('socialMedia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.socialmedia')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
