# Generated by Django 3.2 on 2021-06-30 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0047_auto_20210629_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
