# Generated by Django 3.2 on 2021-07-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0048_unit_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='isButton',
            field=models.BooleanField(default=False),
        ),
    ]
