# Generated by Django 3.2 on 2021-07-02 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0049_category_isbutton'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='career.company'),
        ),
    ]
