# Generated by Django 3.2 on 2021-07-28 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0050_lecture_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='creationDate',
        ),
        migrations.RemoveField(
            model_name='department',
            name='isDeleted',
        ),
        migrations.RemoveField(
            model_name='department',
            name='modificationDate',
        ),
        migrations.RemoveField(
            model_name='department',
            name='uuid',
        ),
    ]
